# scene
scene: navigate
scene_id: scene0420_01
load_texture: true
obs_num: 0 #2

# robot
robot: Turtlebot
agent_initial_pos: [0, 0, 0]
agent_initial_orn: [0, 0, 0]
agent_target_pos: [-2, 1, 0]

body_width: 0.36  # diameter of base link

# action space
is_discrete: true
velocity: 1.0 # normalized wheel velocity
move_distance: 0.1  #0.05
turn_angle: 0.1 #0.03
joint_control: true

# fixed obstacles: pos:[x,y], orn: eular angles
obs_pos: [[0.5,0.5]] #[[1, 1], [2, 2]]
obs_orn: [[0,0,0]] #[[0, 0, 0], [0, 0, 0]]

# observation space: sensor spec
output: [task_obs]  # if learning, can only handle single modal  #task_obs or rgb
third_person_view: true
external_camera_pos: [2, -0.3, 2.3] #[2, 0, 2.3] #[1, 0, 2.3] 
external_camera_view_direction: [-0.4, 0.3, -0.9] #[-0.3, 0, -0.8] #[-0.5, 0, -0.6] 
image_width: 128
image_height: 128

# task
task: navigate_goal_fixed
goal_format: cartesian
task_obs_dim: 12 # basic dimensions in state

# reward
use_goal_dist_reward: false
goal_dist_reward_weight: 1.0 # should > 0

success_reward: 10.0
dist_tol: 0.1 # l2 distance in meter

collision_penalty: -1.0
time_elapse_reward: -1.0
out_of_bound_reward: -10.0

# episode termination condition
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links
visual_object_visible_to_agent: false # visual target landmarks

# simulation
action_timestep: 0.1  # environment executes action per action_timestep second
physics_timestep: 0.025 # physics timestep for pybullet

# rl
# general training settings
training_timesteps: 40000
discount_factor: 0.99
learning_rate: 0.001
minibatch_size: 64
frame_stack: 4

# dqn
update_frequency: 1
target_update_frequency: 100
replay_start_size: 1000
replay_buffer_size: 10000
initial_exploration: 1.0
final_exploration: 0.0
final_exploration_frame: 10000




