# scene
scene: relocate
scene_id: scene0420_01
load_texture: true
obj_num: 2

# robot
robot: Turtlebot
agent_initial_pos: [0, 0, 0]
agent_initial_orn: [0, 0, 0]

# action space
is_discrete: true
velocity: 1.0
move_distance: 0.1  #0.05
turn_angle: 0.1 #0.03
joint_control: true

# objects
obj_initial_pos: [[1, 1], [2, 2]]
obj_initial_orn: [[0, 0, 0], [0, 0, 0]]
obj_target_pos: [[-1, -1], [-2, -2]]
obj_target_orn: [[0, 0, 0], [0, 0, 0]]

# observation space: sensor spec
output: [task_obs, rgb]
external_camera_pos: [2, -0.3, 2.3] #[2, 0, 2.3] #[1, 0, 2.3] 
external_camera_view_direction: [-0.4, 0.3, -0.9] #[-0.3, 0, -0.8] #[-0.5, 0, -0.6] 

# task
task: relocate_point_goal_fixed
target_dist_min: 1.0
target_dist_max: 10.0
goal_format: polar
task_obs_dim: 4

# reward
reward_type: l2
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.1

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36  # body width
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

# visual objects
visual_object_visible_to_agent: false
