# scene
scene: relocate
scene_id: scene0420_01
load_texture: true
obj_num: 2
duplicated_objects: true


# robot
robot: Turtlebot
agent_initial_pos: [0, 0, 0]
agent_initial_orn: [0, 0, 0]
body_width: 0.36  # diameter of base link

# action space
is_discrete: true
velocity: 1.0 # normalized wheel velocity
move_distance: 0.1  #0.05
turn_angle: 0.1 #0.03
joint_control: true

# objects: pos:[x,y], orn: eular angles
obj_initial_pos: [[1, 1], [2, 2]]
obj_initial_orn: [[0, 0, 0], [0, 0, 0]]
obj_target_pos: [[-1, -1], [-2, -2]]
obj_target_orn: [[0, 0, 0], [0, 0, 0]]

# observation space: sensor spec
output: [task_obs, rgb]
third_person_view: true
external_camera_pos: [2, -0.3, 2.3] #[2, 0, 2.3] #[1, 0, 2.3] 
external_camera_view_direction: [-0.4, 0.3, -0.9] #[-0.3, 0, -0.8] #[-0.5, 0, -0.6] 

# task
task: relocate_point_goal_fixed
goal_format: cartesian
task_obs_dim: 12 # basic dimensions in state

# reward
use_goal_dist_reward: true
rot_dist_reward_weight: 0.2 # (position distance reward weight is 1)
goal_dist_reward_weight: 1.0 # should > 0

success_reward: 10.0
dist_tol: 0.1 # l2 distance in meter
angle_tol: 0.2 # eular angle distance ?

collision_penalty: -1.0
collision_reward: 0.1
time_elapse_reward: -0.01
out_of_bound_reward: -10.0


# termination condition
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

# visual target landmarks
visual_object_visible_to_agent: false

# rl
# discount factor
discount_factor: 0.99
# dqn

